2019-09-19 17:19:04,111 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\chatbot.py:58: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-09-19 17:19:04,125 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\hparams.py:19: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

2019-09-19 17:19:04,128 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\hparams.py:21: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

2019-09-19 17:19:04,712 : WARNING : 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-09-19 17:19:04,795 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\botpredictor.py:39: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-09-19 17:19:04,825 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\tokenizeddata.py:158: DatasetV1.make_initializable_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_initializable_iterator(dataset)`.
2019-09-19 17:19:04,832 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\modelcreator.py:34: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

2019-09-19 17:19:04,834 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\modelhelper.py:27: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

2019-09-19 17:19:04,836 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\modelhelper.py:28: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

2019-09-19 17:19:04,848 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\modelhelper.py:35: GRUCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.GRUCell, and will be replaced by that in Tensorflow 2.0.
2019-09-19 17:19:04,853 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\modelhelper.py:57: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
2019-09-19 17:19:04,856 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\modelcreator.py:157: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
2019-09-19 17:19:04,921 : WARNING : Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x0000000024D3F898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x0000000024D3F898>>: AttributeError: module 'gast' has no attribute 'Num'
2019-09-19 17:19:04,939 : WARNING : From C:\ProgramData\Anaconda3\envs\MyPhDChatbot_3.6\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py:564: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-09-19 17:19:04,951 : WARNING : From C:\ProgramData\Anaconda3\envs\MyPhDChatbot_3.6\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py:574: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-09-19 17:19:05,009 : WARNING : Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x0000000022FF6C88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x0000000022FF6C88>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-09-19 17:19:05,102 : WARNING : Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x0000000022FFF048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x0000000022FFF048>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-09-19 17:19:05,117 : WARNING : From C:\ProgramData\Anaconda3\envs\MyPhDChatbot_3.6\lib\site-packages\tensorflow\python\ops\rnn.py:244: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2019-09-19 17:19:05,258 : WARNING : Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000000024BFD5F8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000000024BFD5F8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-09-19 17:19:05,478 : WARNING : Entity <bound method AttentionWrapper.call of <tensorflow.contrib.seq2seq.python.ops.attention_wrapper.AttentionWrapper object at 0x0000000024BAC160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method AttentionWrapper.call of <tensorflow.contrib.seq2seq.python.ops.attention_wrapper.AttentionWrapper object at 0x0000000024BAC160>>: AttributeError: module 'gast' has no attribute 'Num'
2019-09-19 17:19:05,493 : WARNING : Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x0000000024D89630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x0000000024D89630>>: AttributeError: module 'gast' has no attribute 'Num'
2019-09-19 17:19:05,575 : WARNING : Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x0000000024C64748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x0000000024C64748>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-09-19 17:19:05,745 : WARNING : Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x0000000024D76FD0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x0000000024D76FD0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-09-19 17:19:05,863 : WARNING : Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000000024DE7400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000000024DE7400>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-09-19 17:19:05,970 : WARNING : Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000000024CFCB70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000000024CFCB70>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-09-19 17:19:06,001 : WARNING : From C:\ProgramData\Anaconda3\envs\MyPhDChatbot_3.6\lib\site-packages\tensorflow\contrib\seq2seq\python\ops\beam_search_decoder.py:985: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2019-09-19 17:19:06,138 : WARNING : From C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\chatbot\modelcreator.py:97: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2019-09-19 17:19:06,157 : WARNING : From C:\ProgramData\Anaconda3\envs\MyPhDChatbot_3.6\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-09-19 17:19:06,161 : INFO : Restoring parameters from C:\workspace-chatbot\UI\MyPhD-Chatbot\Chatbot_3.6\Data\Result\basic
